
services:
  OrbitelApi:
    image: orbitel-api
    build:
      context: .
      dockerfile: OrbitelApi/Dockerfile
    ports:
      - "8080:8080"
    container_name: orbitel_api
    environment:
      DB_HOST: orbtielapi-postgres-1
      DB_PORT: 5432
      DB_NAME: orbitel
      DB_USER: sa
      DB_PASSWORD: sa
    networks:
      - ping-pong-network
networks:
    ping-pong-network:
      driver: bridge